#### initialization ####
# # setting env
set-option -g default-command "bash --rcfile ~/.bashrc"
set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"
setw -g mouse on
set -g history-limit 10000
 
# hooks
set -g monitor-activity on 
set -g activity-action current 

# refresh on activity
set-hook -g alert-activity 'run-shell "tmux refresh-client -S"'
set -g status-interval 0 # dont refresh periodically

#### layout ####
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on


################
### bindings ###
################
# meta
bind r source-file "~/.config/tmux/tmux.conf" \; display-message "Config reloaded!"
bind a new-session
unbind t ; bind t command-prompt "rename-window '%%'"

# Bind window numbers to the appropriate keys for an AZERTY layout
unbind & ; bind & select-window -t 1
unbind é ; bind é select-window -t 2
unbind '"' ; bind '"' select-window -t 3
unbind "'" ; bind "'" select-window -t 4
unbind ( ; bind ( select-window -t 5
unbind - ; bind - select-window -t 6
unbind è ; bind è select-window -t 7
unbind _ ; bind _ select-window -t 8
unbind ç ; bind ç select-window -t 9

# splits
bind v split-window -h -c "#{pane_current_path}" # vertical split
bind b split-window -v -c "#{pane_current_path}" # horizontal split

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
unbind l
bind l select-pane -R

unbind H ;	bind H resize-pane -L 15
unbind J ;	bind J resize-pane -D 5
unbind K ;	bind K resize-pane -U 5
unbind L ;	bind L resize-pane -R 15

# copy mode
bind y copy-mode
bind P paste-buffer

##############
#### rice ####
##############

# colors
set -g @light-blue "#83a6f2"
set -g @dark-blue "#222436"
set -g @orange "#aba1ed"
set -g @white "#e0e6ff"
set -g @grey "#39415D"


# copy mode
setw -g mode-style 'bg=#{@light-blue},fg=#{@dark-blue}'

# borders
set-option -g pane-border-style 'fg=#{@dark-blue}'
set-option -g pane-active-border-style 'fg=#{@light-blue}'

# status bar
set-option -g status-position top
set -g status-bg '#222436' # background

# status bar left
set-option -g window-status-separator ""
set -g window-status-activity-style "" # disable color-invert

set -g status-left-length 25 # reserve space for the directory name

set -g status-left \
'#[fg=#{@orange}]\
#[bg=#{@dark-blue}]\
\
#[bg=#{@orange}]\
#[fg=#{@dark-blue}]\
󰝰 #(basename #{pane_current_path})\
#[fg=#{@orange}]\
#[bg=#{@dark-blue}]\
 '


set -g window-status-format \
'#[fg=#{@light-blue}]\
#[bg=#{@dark-blue}]\
\
#[bg=#{@light-blue}]\
#[fg=#{@dark-blue}]\
 #W\
#[fg=#{@light-blue}]\
#[bg=#{@dark-blue}]\
'


set -g window-status-current-format \
'#[fg=#{@light-blue}]\
#[bg=#{@dark-blue}]\
\
#[bg=#{@light-blue}]\
#[fg=#{@dark-blue}]\
 #W\
#[fg=#{@light-blue}]\
#[bg=#{@dark-blue}]\
'


# status right
set -g status-right \
'#(
c1="#[fg=#{@light-blue} bg=#{@dark-blue}]"
c2="#[bg=#{@light-blue} fg=#{@dark-blue}]"
s="${c1}${c2}"
e="${c1}"

if ls -ld "#{pane_current_path}/.git" >/dev/null; then
	branch=$(git -C "#{pane_current_path}"  rev-parse --abbrev-ref HEAD)
	git=" $branch"
	git="${s}${git}${e}"
fi

sess=" #S"
sess="${s}${sess}${e}"

host="${s} #{host}${e}"
echo "${git}${sess}${host}"
)'
