preload = ~/.config/hypr/ressources/images/background.png
wallpaper = , ~/.config/hypr/ressources/images/background.png
# preload = ~/.config/hypr/ressources/images/skonewp-ultrawide.png
# wallpaper = , ~/.config/hypr/ressources/images/skonewp-ultrawide.png
