# hyprsunset config

profile {
    time = 08:00
    temperature = 6000
}

profile {
    time = 19:00
    temperature = 4500
	gamma = 0.8
}

profile {
    time = 21:00
    temperature = 4000
	gamma = 0.8
}

profile {
    time = 02:00
    temperature = 1000
	gamma = 0.5
}

# | Variable    | Description                                                                | Type   | Default |
# |-------------|----------------------------------------------------------------------------|--------|---------|
# | time        | The time at which the profile should be activated. Must be in the format   | string | 00:00   |
# |             | {hours}:{minutes}                                                          |        |         |
# | temperature | The screen temperature. Lower means warmer.                                | int    | 6000    |
# | gamma       | The perceived brightness of the screen. This will allow you to lower the   | float  | 1.0     |
# |             | brightness beyond your screen’s minimum.                                   |        |         |
# | identity    | When set, the value of temperature is ignored and the only effect of       | bool   | false   |
# |             | hyprsunset is the change in apparent brightness by gamma.                  |        |         |
