background {
    monitor =
    path = color
    color = rgba(35, 32, 54, 1)
    # blur_passes = 10
}

# background {
#     monitor =
#     path = ~/.config/hypr/ressources/images/skonewp-ultrawide.png
#     blur_passes = 2
#     contrast = 0.55
#     brightness = 0.65
# }

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(83a6f2ee)
    check_color=rgba(ff9e64ee)
    fail_color=rgba(f7768eee)

    font_color = rgb(c0caf5)
    fade_on_empty = false
    rounding = 15

    position = 0, -100
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A %d %B")"
    color = rgb(c0caf5)
    font_size = 25
    font_family = DejaVu SansM
    position = 0, 250
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgb(c0caf5)
    font_size = 120
    font_family = DejaVuSansM Nerd Font Propo Bold
	position = 0, 150
    halign = center
    valign = center
}

# vim: set filetype=hyprlang:
